<?php
function superhero_quicksettings_menu(){
	$items = array();
	$items['superhero/settings'] = array(
		'page callback' => 'superhero_quicksettings_settings',
		'page arguments' => array(2),
		'access arguments' => array('access content'),
	);
	$items['superhero/preset/%'] = array(
		'page callback' => 'superhero_quicksettings_preset',
		'page arguments' => array(2),
		'access arguments' => array('access content'),
	);
	$items['superhero/direction/%'] = array(
		'page callback' => 'superhero_quicksettings_direction',
		'page arguments' => array(2),
		'access arguments' => array('access content'),
	);
	$items['superhero/layout/%'] = array(
		'page callback' => 'superhero_quicksettings_layout',
		'page arguments' => array(2),
		'access arguments' => array('access content'),
	);
	return $items;
}

function superhero_quicksettings_settings(){
	// Do no things
	drupal_goto('<front>');
}

function superhero_quicksettings_preset($preset){
	if(!empty($preset)){
		$_SESSION['superhero_default_preset'] = $preset-1;
	}
	drupal_goto('<front>');
}

function superhero_quicksettings_direction($direction){
	if($direction == 'rtl' || $direction == 'ltr'){
		$_SESSION['superhero_default_direction'] = $direction;
	}
	drupal_goto('<front>');
}

function superhero_quicksettings_layout($layout){
	if($layout == 'wide' || $layout == 'boxed'){
		$_SESSION['superhero_default_layout'] = $layout;
	}
	drupal_goto('<front>');
}
/*
** Implement hook_block_info
*/
function superhero_quicksettings_block_info(){
	$blocks['superhero_quicksettings_block'] = array(
		'info' => t('Superhero Quick Settings'),
		'cache' => DRUPAL_CACHE_PER_PAGE,
	);
	return $blocks;
}

/*
** Implement hook_block_view
*/
function superhero_quicksettings_block_view($delta){
	switch ($delta) {
		case 'superhero_quicksettings_block':
			return _superhero_quicksettings_block();
			break;
		default:
			return array('subject'=>'','content'=>'');
		}
}

/*
**Implements hook_theme()
*/
function superhero_quicksettings_theme(&$vars){
	$module_path = drupal_get_path('module', 'superhero_quicksettings');
	$base = array(
		'path' => "{$module_path}/theme",
	);
	return array(
		'superhero_quicksettings' => $base + array(
			'template' => 'block',
			'variables' => array('items'=>NULL),
		)
	);
}

/*
**Helper function to call theme.
*/
function _superhero_quicksettings_block(){
	$pesets = json_decode(base64_decode(theme_get_setting('superhero_presets')));
	$items = array('presets'=>$pesets);
	$block = array(
		'subject' => '',
		'content' => theme('superhero_quicksettings', array('items'=>$items)),
	);
	return $block; 
}